import './globals.css'
import { Lexend_Exa } from 'next/font/google'

const exa = Lexend_Exa({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={exa.className + " no-scrollbar select-none"}>{children}</body>
    </html>
  )
}
