version: "3.8"

services:
  postgresql:
    image: postgres:15.3-alpine3.18
    restart: always
    env_file:
      - .env
    volumes:
      - postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx:1-alpine3.17
    restart: always
    env_file:
      - .env
    volumes:
      - avatars:/var/www/avatars
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - avatars:/var/www/avatars

volumes:
  postgresql:
  avatars:
