version: "3.8"

services:
  postgresql:
    image: postgres:15.3-alpine3.18
    restart: always
    env_file: ./backend/.env
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    build: ./backend
    restart: always
    env_file: ./backend/.env
    volumes:
      - backend_static:/app/static
    ports:
      - 8000:8000

volumes:
  postgresql:
  backend_static:
