"use client";

import Image from "next/image";
import { useState } from "react";
import axios from "axios";
import { enqueueSnackbar } from "notistack";
import { StatusCodes } from "http-status-codes";
import { useRouter } from "next/navigation";

import { OTPInput } from "@/components/common";
import logoPic from "@/images/logos/logo.png";

export default function Home() {
  const [otp, setOTP] = useState("");
  const router = useRouter();

  async function onOTPVerify() {
    try {
      await axios.patch("/auth/otp/verify", { otp });
      router.push("/home");
    } catch (error) {
      const status = error.response.status;
      const isInvalidOTP = status === StatusCodes.UNPROCESSABLE_ENTITY;
      const message = isInvalidOTP ? "Invalid one time password" : "Error";

      enqueueSnackbar(message, { variant: "error" });
    }
  }

  return (
    <main className="relative bg-bg01 text-tx01">
      {/* verivication Section */}
      {
        <div className="fixed inset-0 flex items-center justify-center bg-bg01">
          <div className="no-scrollbar relative flex h-4/5 max-h-[45rem] w-11/12 flex-col items-center justify-between  overflow-auto rounded-2xl border-[1.5px] border-tx05 bg-bg01 xs:h-2/3 sm:w-[30rem]">
            <div className="my-5 text-base font-light uppercase tracking-[8px] sm:my-10 sm:text-xl sm:tracking-[10px] lg:text-2xl">
              paddel smash
            </div>

            <div className="text-center">
              <div className="mb-2 text-sm font-medium uppercase  tracking-[3px] xs:text-base">
                authenticate your account
              </div>
              <div className="mb-3 text-xs font-light uppercase xs:mb-6 xs:text-sm ">
                enter the code generated by your authenticator app
              </div>
            </div>

            <Image
              alt=""
              src={logoPic}
              className="h-32 w-32 xs:h-52 xs:w-52 sm:h-64 sm:w-64"
            />

            <div className="mb-8 flex flex-col items-center sm:mb-16">
              <div className="mb-5 flex space-x-2 xs:mb-12 xs:space-x-2">
                {Array(6)
                  .fill(undefined)
                  .map((_, index) => (
                    <OTPInput
                      key={index}
                      onChange={setOTP}
                      fullValue={otp}
                      index={index}
                      className="h-10 w-7 rounded-lg border-none bg-tx01 text-center text-tx04 outline-none focus:border-none xs:h-16 xs:w-12 xs:rounded-2xl"
                    />
                  ))}
              </div>

              <div>
                <button
                  disabled={!otp}
                  onClick={onOTPVerify}
                  className="text-xl font-extralight tracking-[6px] xs:text-3xl"
                >
                  verify
                </button>
              </div>
            </div>
            <div></div>
          </div>
        </div>
      }
    </main>
  );
}
